sudo: required
services:
        -docker

before_install:
        - docker build -t talyoffe/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run talyoffe/react-test npm test -- --coverage

after_success:
        - docker build -t talyoffe/multi-client ./client
        - docker build -t talyoffe/multi-nginx ./nginx
        - docker build -t talyoffe/multi-server ./server
        - docker build -t talyoffe/multi-worker ./worker

        #Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        #Take those images and push them to dockerhub
        - docker push talyoffe/multi-client
        - docker push talyoffe/multi-nginx
        - docker push talyoffe/multi-server
        - docker push talyoffe/multi-client 
deploy:
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-022585997406
        buclet_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
