sudo: required
services:
        -docker

before_install:
        - docker build -t talyoffe/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run talyoffe/react-test npm test -- --coverage

after_success:
        - docker build -t talyoffe/multi-client ./client
        - docker build -t talyoffe/multi-nginx ./nginx
        - docker build -t talyoffe/multi-server ./server
        - docker build -t talyoffe/multi-worker ./worker

        #Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        #Take those images and push them to docker hub
        - docker push talyoffe/multi-client
        - docker push talyoffe/multi-nginx
        - docker push talyoffe/multi-server
        - docker push talyoffe/multi-client 
