sudo: required
services:
        -docker

before_install:
        - docker build -t talyoffe/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run talyoffe/react-test npm test -- --coverage

after_success:
        - docker build -t talyoffe/multi-client ./client
        - docker build -t talyoffe/multi-nginx ./nginx
        - docker build -t talyoffe/multi-server ./server
        - docker build -t talyoffe/multi-worker ./worker

